from fpdf.enums import XPos, YPos
from fpdf import FPDF


class PDF(FPDF):
    l_margin: float = 10
    r_margin: float = 10

    def header(self):
        self.set_y(3)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        header_right_text = f"TAX YEAR 2022-23"
        self.set_x(-(self.get_string_width(header_right_text) + 8))
        self.cell(self.get_string_width(header_right_text), 10,
                  header_right_text, align="L", border=0, new_x="LMARGIN", new_y="NEXT")

    def footer(self):
        # Position cursor at 1.5 cm from bottom:
        self.set_y(-12)
        # Setting font: helvetica italic 8
        self.set_font("helvetica", "I", 8)
        # get page width using predefined method
        page_w = self.w

        # footer text
        footer_text = "generated by revbook "
        self.set_text_color(140, 140, 140)
        self.cell(self.get_string_width(footer_text), 10,
                  footer_text, align="L", border=False, new_x="RIGHT")

        # Printing page number:
        page_number_string = f"Page {self.page_no()}/{{nb}}"
        self.set_x(-(self.get_string_width(page_number_string) + 10))
        self.cell(self.get_string_width(page_number_string), 10,
                  page_number_string, align="L", border=False, new_x="RIGHT")

        # self.cell(self)
    def left_para(self, heading_name=None, description=None, heading_font_size=18, desc_font_size=9, border_value=0, head_style="", desc_style=''):
        # pdf.set_text_color(100,100,100)
        header_right_text = heading_name
        if header_right_text:
            self.set_font("helvetica", head_style, heading_font_size)
            self.set_x(self.l_margin)
            self.cell(self.get_string_width(header_right_text), 5, header_right_text,
                      align="L", border=border_value, new_x="LMARGIN", new_y="NEXT")

        if description:
            self.set_font("helvetica", desc_style, desc_font_size)
            description_text = description
            # self.set_x(pdf.l_margin)
            self.cell((self.w//2) - ((self.l_margin*2) + self.r_margin), 5, description_text,
                      align="L", border=border_value, new_x="LMARGIN", new_y="NEXT")

    def right_para(self, heading_name=None, description=None, heading_font_size=18, desc_font_size=9, border_value=0, head_style="", desc_style=''):
        # pdf.set_text_color(100,100,100)
        self.set_x((self.w//2) + (self.l_margin//2))
        header_right_text = heading_name
        if header_right_text:
            self.set_font("helvetica", head_style, heading_font_size)
            rr = (self.w//2) + (self.l_margin//2)
            self.cell(self.get_string_width(header_right_text), 10, header_right_text,
                      align="L", border=border_value, new_x="LEFT", new_y="NEXT")

        if description:
            self.set_font("helvetica", desc_style, desc_font_size)
            description_text = description
            # self.set_x(pdf.l_margin)
            self.cell((self.w//2) - ((self.l_margin*2) + self.r_margin), 5, description_text,
                      align="L", border=border_value, new_x="LMARGIN", new_y="NEXT")


pdf3 = PDF('L', 'mm', 'Letter')
# pdf.set_left_margin(10)
# pdf.set_right_margin(10)

pdf3.add_page()
pdf3.left_para(heading_name="Income summary",
               description="Summary of any income you may have earnt from various crypto events  ", heading_font_size=15, head_style="B")
pdf3.left_para(
    description="during the tax year. ", heading_font_size=12, head_style="B")

pdf3.left_para(description=" ", border_value=0)

pdf3.left_para(heading_name="Airdrop",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Fork",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Mining",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Reward",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Loan interest ",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Other income",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Total",
               description=" ", heading_font_size=12, head_style="B")

pdf3.left_para(description=" ", border_value=0)

pdf3.left_para(heading_name="Expenses",
               description="These costs have not been included in your capital gains but you may be ", heading_font_size=15, head_style="B")
pdf3.left_para(
    description="able to deduct them elsewhere on your tax return. Trading fees are ")
pdf3.left_para(
    description=" already included in the capital gains and will not be shown here.")
pdf3.left_para(description=" ", border_value=0)
# pdf3.left_para(description=" ", border_value=0)


pdf3.left_para(heading_name="Cost",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Margin trade fee ",
               description=" ", heading_font_size=12, head_style="B")


pdf3.left_para(heading_name="Margin interest fee",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Transfer fees",
               description=" ", heading_font_size=12, head_style="B")
pdf3.left_para(heading_name="Total",
               description=" ", heading_font_size=12, head_style="B")

pdf3.set_y(10)


pdf3.right_para(heading_name="Gifts, donations & lost assets",
                description="This section shows you the value of transactions tagged as Gift, ", heading_font_size=12, head_style="B")
pdf3.right_para(
    description="(Donation or Lost. No capital gains are realized on such transactions")
pdf3.right_para(
    description="((remove the tags if you need to realize gains on them).")
pdf3.right_para(heading_name="Gift",
                description=" ", heading_font_size=12, head_style="B", border_value=0)
pdf3.right_para(heading_name="Lost ",
                description=" ", heading_font_size=12, head_style="B", border_value=0)
pdf3.right_para(heading_name="Donation",
                description=" ", heading_font_size=12, head_style="B", border_value=0)
pdf3.right_para(heading_name="Total",
                description=" ", heading_font_size=12, head_style="B", border_value=0)


pdf3.output("pdf_3.pdf")
print("File saved")

# must set the cursor y-position separately before the left_para method for new right para (x position is already set in the method)
# sets the position from TOP of the page (from the bottom of page if value is negative)
